### ISSUE TITLE
Travis CI test workspace cleanup

### ISSUE THREAD

**Issue by hjwilli** [EpistasisLab/pennai#218] opened 2019-07-11 15:47 UTC
Some unit tests are passing in the Travis CI environment but not the Jenkins CI environment (see #175).  The test failures are due to some files being removed in github but the tests not being properly updated.  

Jenkins is correctly giving a file not found error.  Travis logs show that the tests ran successfully, it seems like the files were still in the Travis unit test workspace.

**Comment by weixuanfu** [comment] 2019-07-11 17:36
@hjwilli The same errors were also captured in log of Travis CI (see this [link]) and it should failed but somehow we save the reports into html/xml file so there is no failed signal in Travis CI. I will fix Travis CI part. But there is still a bug related to the error.

**Comment by weixuanfu** [comment] 2019-07-11 18:23
@hjwilli 
I think [this function](https://github.com/EpistasisLab/pennai/blob/v0.13/ai/tests/test_recommender.py#L38-L55) in test_recommander.py need to be refactored since those metafeature json files were removed.

**Comment by hjwilli** [comment] 2019-07-11 19:39
Hi @weixuanfu, thanks for finding this!  The test_recommender.py fixes are noted in #175, I'll update them.  The Travis bug needed to be addressed as a separate issue.

**Comment by weixuanfu** [comment] 2019-07-11 19:42
@hjwilli I just pushed a commit above to fix the Travis bug. The issue is that docker-compose can only expose the exit code 1 (error) if the error happens the last line of bash scripts 'unit_test_runner.sh'. So I refined that scripts a little bit.

**Comment by weixuanfu** [comment] 2019-07-29 19:44
I close this issue since it is fixed and merged into master branch.

**Closed by weixuanfu** 2019-07-29 19:44 UTC
