### ISSUE TITLE
unit test runner is failing

### ISSUE THREAD

**Issue by mgstauffer** [EpistasisLab/pennai#312] opened 2021-02-05 23:45 UTC
In current master branch. Attaching a shell to a running docker container and running the unit test runner generates these errors:

```
root@dcbe16be5338:/appsrc# sh tests/unit/unit_test_runner.sh
: not foundunit_test_runner.sh: 2: tests/unit/unit_test_runner.sh:
: not foundunit_test_runner.sh: 6: tests/unit/unit_test_runner.sh:
: not foundunit_test_runner.sh: 7: tests/unit/unit_test_runner.sh:
: not foundunit_test_runner.sh: 19: tests/unit/unit_test_runner.sh:
: not foundunit_test_runner.sh: 21: tests/unit/unit_test_runner.sh:
: not foundunit_test_runner.sh: 25: tests/unit/unit_test_runner.sh:
mkdir: cannot create directory ‘target/test-reports/cobertura/html\r’: Input/output error
mkdir: cannot create directory ‘target/test-reports/html\r’: Input/output error
: not foundunit_test_runner.sh: 28: tests/unit/unit_test_runner.sh:
starting nosetest
 lab/pyutils/tests/test_validateDataset.pys.pyy
: not foundunit_test_runner.sh: 31: tests/unit/unit_test_runner.sh:
tests/unit/unit_test_runner.sh: 32: tests/unit/unit_test_runner.sh: coverage: not found
tests/unit/unit_test_runner.sh: 33: tests/unit/unit_test_runner.sh: --with-xunit: not found
tests/unit/unit_test_runner.sh: 34: tests/unit/unit_test_runner.sh: --with-html: not found
tests/unit/unit_test_runner.sh: 35: tests/unit/unit_test_runner.sh: -v: not found
: not foundunit_test_runner.sh: 38: tests/unit/unit_test_runner.sh:
tests/unit/unit_test_runner.sh: 39: tests/unit/unit_test_runner.sh: coverage: not found
tests/unit/unit_test_runner.sh: 40: tests/unit/unit_test_runner.sh: coverage: not found
tests/unit/unit_test_runner.sh: 41: tests/unit/unit_test_runner.sh: coverage: not found
: not foundunit_test_runner.sh: 42: tests/unit/unit_test_runner.sh:
coverage erase
tests/unit/unit_test_runner.sh: 44: tests/unit/unit_test_runner.sh: coverage: not found
: not foundunit_test_runner.sh: 45: tests/unit/unit_test_runner.sh:
starting mocha tests
tests/unit/unit_test_runner.sh: 47: tests/unit/unit_test_runner.sh: mocha: not found
: not foundunit_test_runner.sh: 48: tests/unit/unit_test_runner.sh:
: not foundunit_test_runner.sh: 49: tests/unit/unit_test_runner.sh:
: not foundunit_test_runner.sh: 52: tests/unit/unit_test_runner.sh:
starting lab jest reports
tests/unit/unit_test_runner.sh: 54: cd: can't cd to /appsrc/lab/
npm ERR! path /appsrc/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/appsrc/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-05T23_01_08_895Z-debug.log
: not foundunit_test_runner.sh: 56: tests/unit/unit_test_runner.sh:
: not foundunit_test_runner.sh: 57: tests/unit/unit_test_runner.sh:
starting webapp jest reports
tests/unit/unit_test_runner.sh: 59: cd: can't cd to /appsrc/lab/webapp/
npm ERR! path /appsrc/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/appsrc/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-05T23_01_09_126Z-debug.log
: not foundunit_test_runner.sh: 61: tests/unit/unit_test_runner.sh:
```

**Comment by hjwilli** [comment] 2021-02-10 19:53
Hi @mgstauffer , this might be caused by your local version of unit_test_runner.sh having windows (CLRF) line endings.

Try running dos2unix first and see if you get the same error ( `dos2unix tests/unit/unit_test_runner.sh && sh tests/unit/unit_test_runner.sh`)

If you run the unit tests using `docker-compose-unit-tests.yaml` instead of attaching to a running container, this happens automatically.

**Comment by mgstauffer** [comment] 2021-02-17 22:24
@hjwilli Interesting! After converting to unix line endings, I'm still getting the `coverage: not found` error for nosetest. But the other tests are running. I think Weixuan said the `coverage: not found` was due to something else? 

I looked in `.gitattributes` and it does not have the `text=auto` option set to have line endings converted to linux formating on upload/push. Do we want that? I do see that it is setting some files like .sh files to always checkout with LF line endings. I must have edited my local version with a windows editor at some point. Do you know if now I need to commit the changes to the files' line endings and push up again?

**Comment by hjwilli** [comment] 2021-02-18 18:11
> 
> 
> @hjwilli Interesting! After converting to unix line endings, I'm still getting the `coverage: not found` error for nosetest. But the other tests are running. 

Seems like it doesn't see the `coverage` python package, which is part of the testing dependencies that are only installed as part of the [unit test docker image](https://github.com/EpistasisLab/pennai/blob/460f04e7c13b00539ec0f8326fb171deb14c39e8/tests/unit/requirements.txt).  How are you running the tests (which compose file are you using) and what branch are you in?  Does `docker-compose-unit-tests.yaml` work?

> I must have edited my local version with a windows editor at some point. Do you know if now I need to commit the changes to the files' line endings and push up again?

This is likely what happened.  You shouldn't need to re-commit.

**Comment by hjwilli** [comment] 2021-02-19 22:12
Hi @mgstauffer .  Made some updates related to this in PR https://github.com/EpistasisLab/pennai/pull/314 , which has been merged to master.  You can now use `/tests/unit/js_tests.sh` to run just the javascript unit tests.

**Comment by mgstauffer** [comment] 2021-02-19 22:15
Thanks! Updating now

**Comment by hjwilli** [comment] 2021-04-16 20:35
resolved!

**Closed by hjwilli** 2021-04-16 20:35 UTC
